sudo: required
services:
    -docker
 
 before_install:
    - docker build -t gamanma/docker-aws -f Dockerfile.dev .
    
script:
    - docker run -e CI=true USERNAME/docker-react npm run test

language: generic 